### ISSUE TITLE
Create a release with attached tgz to make inclusion in pipeline easier

### ISSUE THREAD

**Issue by lisamburns** [cloudfoundry-incubator/bits-service-release#15]
CAPI team has started testing the bits-service integration with CC. Creating a GitHub release with an attached BOSH release tarball would make it easier to include into our pipeline. This release could also be included in [this ops file](https://github.com/cloudfoundry/cf-deployment/blob/5ef5b808ad82c8251d9b093f6dce3df8b456b79f/operations/experimental/bits-service.yml#L98) to avoid creating a dev release out of band.

**Comment by elenasharma** [comment]
Is this done? 😺

**Comment by petergtz** [comment]
@elenasharma yes. This is done. Please check the releases tab. Also we've updated the ops file with a link to the GitHub release as requested. I'm closing this issue now. Feel free to open if you think something is missing.
