### ISSUE TITLE
nginx job complains about `server_names_hash_bucket_size`

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry-incubator/bits-service-release#16]
I deployed CF on a bosh-lite VM using cf-deployment (SHA 36738ba9a4fc407a3eaef60604ca8e935efcb562) and the following ops files:

* operations/experimental/bits-service.yml 
* operations/experimental/enable-bits-service-https.yml
* operations/experimental/bits-service-webdav.yml
* operations/experimental/enable-bits-service-consul.yml

The `nginx_bits` job on the api instance group was failing, reporting that `server_names_hash_bucket_size` needed to be increased. Changing this value to 128 in nginx.conf and restarting all the jobs allowed the deployment to succeed.

Even after this however, the bits service was not externally accessible, e.g.:

```
$ curl -kv https://bits-service.<system domain>/
*   Trying <ip>...
* Connected to bits-service.<system domain> (IP) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: routerSSL (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=USA,O=Cloud Foundry,CN=routerSSL
*        start date: Tue, 12 Dec 2017 11:57:50 GMT
*        expire date: Wed, 12 Dec 2018 11:57:50 GMT
*        issuer: C=USA,O=Cloud Foundry,CN=routerCA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: bits-service.<system domain>
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 264
< Content-Type: text/html
< Date: Tue, 12 Dec 2017 15:05:00 GMT
< Server: nginx
< X-Vcap-Request-Id: d4090290-9d51-4a61-450b-e6dbfa992241
<
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host bits-service.<system domain> left intact
```

**Comment by petergtz** [comment]
@craigfurman Thanks for reporting this. This issue is probably related to [nginx' `server_names_hash_bucket_size` property](http://nginx.org/en/docs/http/server_names.html#optimization). We'll provide a fix quite soon.

For our education, what's the string length of the system-domain you're using?

Thanks,
Peter

**Comment by craigfurman** [comment]
Hi Peter,

Yes, changing server_names_hash_bucket_size to 128 (but not 64) fixed this. My system domain was 34 characters long.

**Comment by petergtz** [comment]
@craigfurman Okay. Config is fixed. Our pipeline is currently red for other reasons. So we can't release this yet. But if you're actually creating the release yourself anyways, then this issue is resolved. What do you think?

**Comment by craigfurman** [comment]
Looks good!
