### ISSUE TITLE
Missing instructions to download dependencies locally of bitsgo

### ISSUE THREAD

**Issue by MissingRoberto** [cloudfoundry-incubator/bits-service-release#17]
Not sure if I missed something, but I had to run glide install in `bits-service` to download the dependencies. 

That's not mentioned in the Readme at all afaik

**Comment by petergtz** [comment]
Hi @jszroberto,

That documentation sits in github.com/cloudfoundry-incubator/bits-service because we treat the fact that it is written in Go as an implementation detail, not part of the Bosh release. Also, for creating the Bosh release the glide call is not necessary.

Is that sufficient or do you see a problem with that?

**Comment by MissingRoberto** [comment]
well, you have the instructions in this repository to run the tests, but to run them you need to do "glide install" first.

BTW, I am not sure if you need to run: 
```
bundle install
bundle exec rake
```
for that any longer. 

I am referring to this section: https://github.com/cloudfoundry-incubator/bits-service-release#run-tests

**Comment by petergtz** [comment]
Ah, yes, the fact that those acceptance tests are in the Bosh release is an ugly left-over which we just haven't had the time to address yet. We planned to move them out of the bosh release completely and make a dedicated bits-service-acceptance-tests repo which would also include other kinds of tests (performance, migration etc.). So eventually this repo will really just be Bosh, nothing else. Sorry about that ugly artifact.

**Comment by idev4u** [comment]
@pego There is other issues in the documentations, too.
```
./scripts/generate-cf-with-bits-service-enabled-bosh-lite-manifest local --size-limits
-bash: ./scripts/generate-cf-with-bits-service-enabled-bosh-lite-manifest: No such file or directory
```
I will made a note in the PT, too.

**Comment by petergtz** [comment]
@jszroberto @idev4u I'm closing this issue for now. There is no plan to fix this at this point. Feel free to re-open or provide a PR, in case you think this still makes sense.
