### ISSUE TITLE
Golang update

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry-incubator/bits-service-release#18]
Hello,

I see you are [using an old version of Go](https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/config/blobs.yml) and our vulnerability scan complains about it.

Even though most CVEs won't apply to this specific implementation, would still be nice to have it updated to 1.11.5

Thanks!

**Comment by petergtz** [comment]
@michaelgrifalconi I've moved this into our backlog. Since there are no immediate CVEs attached to it, it's not at the top, but we'll address it in time.

**Comment by petergtz** [comment]
This is completed.
