### ISSUE TITLE
Support external dns and cert manager

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/bits-service-release#33]
Hi there,

We got a PR  https://github.com/cloudfoundry-incubator/eirini-release/pull/81 which simplifies certificate management. Since you have extracted bits service helm chart, it makes sense for you to implement this feature. This significantly helps operators to use the bits service as a registry.

cc original PR author @paurczar

**Comment by petergtz** [comment]
@alex-slynko Thanks for the heads-up. I think in general that makes sense. I'm wondering when eirini will pick up the chart provided by bits instead of using its own bits helm chart? We'd be avoiding this duplicate work.

**Comment by alex-slynko** [comment]
@petergtz we've switched to the bits service chart in master already.

**Comment by alex-slynko** [comment]
Reopen the issue to test the integration

**Comment by alex-slynko** [comment]
This is working now! Cool!
